### ISSUE TITLE
MeetCMBScreenPlay

### ISSUE THREAD

**Issue by kunoichiI** [kunoichiI/MeetCMB#1]
![meetcmbscreenplay](https://cloud.githubusercontent.com/assets/10201379/20290566/a98e83bc-aa95-11e6-8e7a-0b46023e3d98.gif)

**Comment by geek-paulwong** [comment]
Lol, it's been a while ;)

**Comment by geek-paulwong** [comment]
I remember, we were coding together, in your ex-landlord's kitchen on the 2nd floor, bahaha!
